version: "3"
services:
    db:
        image: mariadb:10.3.2
        restart: always
        environment:
            MYSQL_USER: kirbot
            MYSQL_PASSWORD: kirbot
            MYSQL_DATABASE: kirbot
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./.data/db:/var/lib/mysql
            - ./conf/mysql:/etc/mysql/conf.d
    redis:
        image: redis:3.2
        restart: always
        volumes:
            - ./.data/redis:/data
    web:
        image: mrkirby153/laravel:latest
        restart: always
        ports:
            - "8580:80"
        volumes:
            - ./KirBotPanel:/var/www
        depends_on:
            - redis
            - db
    bot:
        build: .
        restart: unless-stopped
        volumes:
            - ./.data/kirbot:/kirbot/data
        depends_on:
            - redis
            - web