{
 "title": "KirBot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bot_users", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Websocket Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "websocket_ping" }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bot_users) + sum(bot_bots)" }
   ]
  },
  {
   "title": "Guilds",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bot_guilds" }
   ]
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bot_events)" }
   ]
  },
  {
   "title": "Messages Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(messages_received)" }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(own_messages)" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(own_messages) + sum(messages_received)"
    }
   ]
  },
  {
   "title": "Commands Ran",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "commands_ran", "legendFormat": "{{command_name}}" }
   ]
  },
  {
   "title": "Top 10 Active Guilds",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "messages_received", "legendFormat": "{{guild}}" }
   ]
  },
  {
   "title": "Events",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "bot_events", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bot_users", "legendFormat": "Users" },
    { "expr": "bot_bots", "legendFormat": "Bots" }
   ]
  },
  {
   "title": "Messages Sent [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_received[5m]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Events [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(bot_events[5m]))", "legendFormat": "Events" }
   ]
  },
  {
   "title": "Average Command Execution [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bot_command_timing_sum[5m])) / sum(rate(bot_command_timing_count[5m]))",
     "legendFormat": "Time (ms)"
    }
   ]
  },
  {
   "title": "Average Command Execution Time [5m]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(bot_command_timing_sum[5m]) / rate(bot_command_timing_count[5m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(jvm_threads_state)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area='heap'}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area='heap'}",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}